#ifndef CONFIGURATION_H
#define CONFIGURATION_H

class Configuration {
public:
    Configuration();
    //CONVERSIONS
    float DEGTORAD;
    float SCALING_FACTOR;

    //WORLD
    float WORLD_TIME_STEP;
    float WORLD_VELOCITY_ITERATIONS;
    float WORLD_POSITION_ITERATIONS;
    
    //WORM
    float WORM_SPEED;

    //BAZOOKA
    int BAZOOKA_BLAST_RADIUS;
    int BAZOOKA_BLAST_POWER;

    //MORTAR
    int MORTAR_BLAST_RADIUS;
    int MORTAR_BLAST_POWER;
    int MORTAR_FRAGMENT_QUANTITY;
    int MORTAR_FRAGMENT_BLAST_RADIUS;
    int MORTAR_FRAGMENT_BLAST_POWER;

    //RED GRENADE
    int RED_GRENADE_BLAST_RADIUS;
    int RED_GRENADE_BLAST_POWER;
    int RED_GRENADE_FRAGMENT_QUANTITY;
    int RED_GRENADE_FRAGMENT_BLAST_RADIUS;
    int RED_GRENADE_FRAGMENT_BLAST_POWER;

    //BANANA
    int BANANA_BLAST_RADIUS;
    int BANANA_BLAST_POWER;

    //HOLY GRENADE
    int HOLY_GRENADE_BLAST_RADIUS;
    int HOLY_GRENADE_BLAST_POWER;

    //AIRSTRIKE
    int AIR_STRIKE_BLAST_RADIUS;
    int AIR_STRIKE_BLAST_POWER;
    int AIR_STRIKE_MISSIL_QUANTITY;

    //BAT
    int BAT_DAMAGE;

    //DYNAMITE
    int DYNAMITE_BLAST_RADIUS;
    int DYNAMITE_BLAST_POWER;
    
    //GREEN GRENADE
    int GREEN_GRENADE_BLAST_RADIUS;
    int GREEN_GRENADE_BLAST_POWER;
};

extern Configuration gConfiguration;

#endif